### ISSUE TITLE
Detection not working

### ISSUE THREAD

**Issue by kallitokaco** [HearthStats/HearthStats.net-Uploader#625]
detection isn't working. Changed language from germen to english(US). Even the "To export a deck,navigate..."-Message doesen't appear everytime, i need to resart HS for that.
![image](https://cloud.githubusercontent.com/assets/1846989/5800547/2aac2b9c-9fe0-11e4-8dfc-24b48c5d2bb0.png)

LOG:
13:20:06.876 [    main] WARN      n.h.c.UserConfig - Unable to interpret value en, using default en instead
13:20:07.001 [    main] INFO  .VideoEncoderFactory - Instantiation interface net.hearthstats.modules.video.VideoEncoder from SPI
13:20:07.546 [    main] INFO     n.h.hstatsapi.API - API get result = {"status":"error","message":"User not is not premium"}
13:20:07.553 [    main] ERROR    n.h.hstatsapi.API - User not is not premium
13:20:07.554 [    main] INFO     n.h.hstatsapi.API - You are not a premium user
13:20:07.559 [    main] WARN        n.h.ui.log.Log - <div class="break">&nbsp;</div><div class="warn"><span class="ts">[13:20:07]</span>&nbsp; You don't have premium subscription, videos won't be uploaded to hearthstats.net</div>
13:20:07.560 [    main] INFO  .FileUploaderFactory - Dummy instantiation for interface net.hearthstats.modules.upload.FileUploader :class net.hearthstats.modules.upload.DummyFileUploader
13:20:08.040 [    main] INFO  net.hearthstats.Main - **********************************************************************
13:20:08.041 [    main] INFO  net.hearthstats.Main -   Starting HearthStats Companion 0.21.1 on WINDOWS
13:20:08.042 [    main] INFO  net.hearthstats.Main -   os.name=Windows 7
13:20:08.042 [    main] INFO  net.hearthstats.Main -   os.version=6.1
13:20:08.043 [    main] INFO  net.hearthstats.Main -   os.arch=amd64
13:20:08.044 [    main] INFO  net.hearthstats.Main -   java.runtime.version=1.7.0_09-b05
13:20:08.044 [    main] INFO  net.hearthstats.Main -   java.class.path=C:\Users\kallitokaco\Downloads\HearthStats.net.Uploader.v0.21.1\HearthStats.exe;anything;companion-0.21.1.jar;updater-0.21.1.jar;scala-library-2.11.4.jar;scala-swing_2.11-1.0.1.jar;macros_2.11-0.7.3.jar;scala-reflect-2.11.2.jar;akka-actor_2.11-2.3.6.jar;config-1.2.1.jar;nscala-time_2.11-1.4.0.jar;joda-time-2.4.jar;joda-convert-1.2.jar;grizzled-slf4j_2.11-1.0.2.jar;logback-classic-1.1.2.jar;logback-core-1.1.2.jar;commons-lang3-3.3.1.jar;commons-io-2.4.jar;jna-platform-4.0.0.jar;jna-4.0.0.jar;ini4j-0.5.2.jar;jai_imageio-1.1.jar;javaocr-core-1.0.jar;javaocr-plugin-awt-1.0.jar;javaocr-plugin-cluster-1.0.jar;commons-math-2.1.jar;javaocr-plugin-fir-1.0.jar;javaocr-plugin-moment-1.0.jar;javaocr-plugin-morphology-1.0.jar;json-simple-1.1.1.jar;miglayout-swing-4.2.jar;miglayout-core-4.2.jar;JGoogleAnalyticsTracker-1.2.0.jar;slf4j-api-1.7.6.jar;jackson-module-scala_2.11-2.4.3.jar;jackson-core-2.4.3.jar;jackson-annotations-2.4.3.jar;jackson-databind-2.4.3.jar;paranamer-2.6.jar;jsr305-2.0.1.jar;guava-15.0.jar;video-0.21.1.jar;xuggle-xuggler-5.4.jar;commons-cli-1.1.jar;google-api-services-youtube-v3-rev107-1.18.0-rc.jar;google-api-client-1.18.0-rc.jar;google-oauth-client-1.18.0-rc.jar;google-http-client-jackson2-1.18.0-rc.jar;google-http-client-1.18.0-rc.jar;google-oauth-client-jetty-1.18.0-rc.jar;google-oauth-client-java6-1.18.0-rc.jar;jetty-6.1.26.jar;jetty-util-6.1.26.jar;servlet-api-2.5-20081211.jar;google-collections-1.0.jar;aws-java-sdk-1.6.0.jar;commons-logging-1.1.1.jar;httpclient-4.2.jar;httpcore-4.2.jar;commons-codec-1.3.jar
13:20:08.045 [    main] INFO  net.hearthstats.Main -   java.library.path=C:\Program Files\Java\jre7\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Dev\Toolkitv6\bin;C:\Dev\Toolkitv6\libnvvp;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby1.9.3\bin;C:\Python27\Lib\site-packages\PyQt4;C:\Program Files (x86)\Profactor\ReconstructMeSDK\1.5.795\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Python33\;C:\Program Files (x86)\ActiveState Komodo Edit 7\;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\ThinkPad\Bluetooth Software\;C:\Program Files\ThinkPad\Bluetooth Software\syswow64;Z:\Development\Android\android-ndk-r8b-windows;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\CMake 2.8\bin;C:\WinAVR-20100110\bin;C:\WinAVR-20100110\utils\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\dev\3RDPARTY\OpenSceneGraph\bin;C:\Development\Kinect\SigmaNILFramework\bin;C:\Program Files (x86)\ViiM2\bin;C:\Program Files (x86)\ViiM2\third-party\opencv\libs\bin;C:\Program Files (x86)\ViiM2\bin;C:\Program Files\Instant Reality\bin\;C:\Development\Kinect\OpenNI2_Dev\tags\2.1-Beta\ThirdParty\GL;C:\Development\opencv\build\x86\vc11\bin;C:\Development\OpenNI1\Bin64;C:\Development\OpenNI1\Bin;C:\Program Files\TortoiseSVN\bin;C:\Qt\Desktop\Qt\4.7.3\mingw\bin;C:\Program Files (x86)\gnuplot\bin;C:\openexr-1.7.0\lib\x64;C:\Qt\Qt5.2.1\5.2.1\msvc2012_64_opengl\bin;C:\Assimp\bin\x64;C:\Program Files (x86)\GTK2-Runtime\bin;C:\NVPACK\android-ndk-r10;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\OpenVPN\bin;C:\Development\NVPACK\android-sdk-windows\platform-tools;C:\Development\NVPACK\android-sdk-windows\build-tools;C:\Development\NVPACK\android-sdk-windows\tools;C:\Development\NVPACK\jdk1.6.0_24\bin;C:\Development\NVPACK\apache-ant-1.8.2\bin;C:\Development\NVPACK\android-ndk-r8e\;C:\openexr-1.7.0\lib\x64;C:\Qt\Qt5.2.1\5.2.1\msvc2012_64_opengl\bin;C:\NVPACK\android-sdk-windows\platform-tools;C:\NVPACK\android-sdk-windows\build-tools;C:\NVPACK\android-sdk-windows\tools;C:\NVPACK\jdk1.6.0_45\bin;C:\NVPACK\cygwin\bin;C:\NVPACK\apache-ant-1.8.2\bin;.;;C:\Program Files\Java\jre7\bin;.;;.
13:20:08.045 [    main] INFO  net.hearthstats.Main -   user.language=de
13:20:08.045 [    main] INFO  net.hearthstats.Main - **********************************************************************
13:20:22.249 [tQueue-0] ERROR    n.h.hstatsapi.API - Error communicating with HearthStats.net (GET decks/show)
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.7.0_09]
	at java.net.SocketInputStream.read(Unknown Source) ~[na:1.7.0_09]
	at java.net.SocketInputStream.read(Unknown Source) ~[na:1.7.0_09]
	at java.io.BufferedInputStream.fill(Unknown Source) ~[na:1.7.0_09]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[na:1.7.0_09]
	at java.io.BufferedInputStream.read(Unknown Source) ~[na:1.7.0_09]
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source) ~[na:1.7.0_09]
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source) ~[na:1.7.0_09]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.7.0_09]
	at net.hearthstats.hstatsapi.API._get(API.scala:109) [HearthStats.exe:na]
	at net.hearthstats.hstatsapi.API.getDecks(API.scala:193) [HearthStats.exe:na]
	at net.hearthstats.hstatsapi.DeckUtils.updateDecks(DeckUtils.scala:18) [HearthStats.exe:na]
	at net.hearthstats.ui.DecksTab.updateDecks(DecksTab.scala:79) [HearthStats.exe:na]
	at net.hearthstats.ui.DecksTab$$anonfun$1.apply$mcV$sp(DecksTab.scala:76) [HearthStats.exe:na]
	at scala.swing.Swing$$anon$10.run(Swing.scala:32) [HearthStats.exe:na]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [na:1.7.0_09]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [na:1.7.0_09]
	at java.awt.EventQueue.access$200(Unknown Source) [na:1.7.0_09]
	at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_09]
	at java.awt.EventQueue$3.run(Unknown Source) [na:1.7.0_09]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_09]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [na:1.7.0_09]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [na:1.7.0_09]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.7.0_09]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.7.0_09]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.7.0_09]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_09]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_09]
	at java.awt.EventDispatchThread.run(Unknown Source) [na:1.7.0_09]
13:20:22.253 [tQueue-0] WARN        n.h.ui.log.Log - <div class="warn"><span class="ts">[13:20:22]</span>&nbsp; no deck were returned from Hearthstats.net. Either you have not created a deck or the site is down</div>
13:20:22.410 [    main] INFO        n.h.ui.log.Log - <div class="std"><span class="ts">[13:20:22]</span>&nbsp; Using existing Hearthstone log config C:\Users\kallitokaco\AppData\Local\Blizzard\Hearthstone\log.config</div>
13:20:22.412 [    main] INFO        n.h.ui.log.Log - <div class="break">&nbsp;</div><div class="welcome">HearthStats Companion v0.21.1</div>
13:20:22.413 [    main] INFO        n.h.ui.log.Log - <div class="break">&nbsp;</div><div class="help">1 - Set your deck slots on the "Decks" tab</div>
13:20:22.414 [    main] INFO        n.h.ui.log.Log - <div class="help">2 - Run Hearthstone in <strong>WINDOWED</strong> mode</div>
13:20:22.414 [    main] INFO        n.h.ui.log.Log - <div class="help">3 - Look for event notifications in this log and bottom right of screen</div>
13:20:22.426 [    main] INFO        n.h.ui.log.Log - <div class="help">4 - <a href="http://goo.gl/lMbdzg">Submit feedback here</a> (please copy and paste your log file in C:\Users\kallitokaco\Downloads\HearthStats.net.Uploader.v0.21.1\log.txt)</div>
13:20:22.440 [    main] INFO     n.h.c.GameMonitor - HearthStats Companion started
13:20:22.488 [tQueue-0] INFO        n.h.ui.log.Log - <div class="break">&nbsp;</div><div class="std"><span class="ts">[13:20:22]</span>&nbsp; Checking for updates ...</div>
13:20:22.729 [thread-1] INFO        n.h.ui.log.Log - <div class="std"><span class="ts">[13:20:22]</span>&nbsp; Hearthstone detected</div>
13:20:22.734 [thread-1] INFO    n.h.u.FileObserver - observing file C:\Program Files (x86)\Hearthstone\Hearthstone_Data\output_log.txt
13:20:22.734 [thread-1] INFO        n.h.ui.log.Log - <div class="std"><span class="ts">[13:20:22]</span>&nbsp; Observing Hearthstone log file : C:\Program Files (x86)\Hearthstone\Hearthstone_Data\output_log.txt</div>
13:20:24.171 [tQueue-0] INFO        n.h.ui.log.Log - <div class="std"><span class="ts">[13:20:24]</span>&nbsp; Latest version available: v0.21.1</div>
13:22:25.336 [tQueue-0] INFO     n.h.hstatsapi.API - API get result = {"status":"success","data":[]}
13:22:25.337 [tQueue-0] INFO     n.h.hstatsapi.API - Fetched your decks from HearthStats.net
13:22:25.337 [tQueue-0] WARN        n.h.ui.log.Log - <div class="warn"><span class="ts">[13:22:25]</span>&nbsp; no deck were returned from Hearthstats.net. Either you have not created a deck or the site is down</div>
13:23:50.654 [tcher-10] INFO  earthstoneLogMonitor - game event: GameModeDetected(Casual)
13:23:51.054 [tcher-19] INFO  earthstoneLogMonitor - game event: LegendRank(0)
13:23:57.637 [tcher-18] INFO  earthstoneLogMonitor - game event: LegendRank(0)
13:23:57.665 [tcher-18] INFO  earthstoneLogMonitor - game event: GameModeDetected(Casual)
13:23:57.667 [tcher-18] INFO  earthstoneLogMonitor - game event: LegendRank(0)
13:23:59.845 [thread-1] WARN        n.h.ui.log.Log - <div class="warn"><span class="ts">[13:23:59]</span>&nbsp; Hearthstone not detected</div>
13:23:59.846 [thread-1] INFO    n.h.u.FileObserver - stopped observing file C:\Program Files (x86)\Hearthstone\Hearthstone_Data\output_log.txt
13:24:04.662 [thread-1] INFO        n.h.ui.log.Log - <div class="std"><span class="ts">[13:24:04]</span>&nbsp; Hearthstone detected</div>
13:24:04.662 [thread-1] INFO    n.h.u.FileObserver - observing file C:\Program Files (x86)\Hearthstone\Hearthstone_Data\output_log.txt
13:24:04.663 [thread-1] INFO        n.h.ui.log.Log - <div class="std"><span class="ts">[13:24:04]</span>&nbsp; Observing Hearthstone log file : C:\Program Files (x86)\Hearthstone\Hearthstone_Data\output_log.txt</div>
13:24:07.508 [tcher-16] INFO  earthstoneLogMonitor - game event: LegendRank(0)

**Comment by tyrcho** [comment]
You are trying to export a deck to the site, right ? 

You need to select (click on the title) the deck you want to export from the game, only one deck is exported at a time.

**Comment by kallitokaco** [comment]
Exactly, tried this too, didn't change anything. Btw. detection of matches worked only for cards, gamemode and rank couldn't be detected. ![image](https://cloud.githubusercontent.com/assets/1846989/5800735/e4aff602-9fe2-11e4-8e90-5e0ebfce7d61.png)

**Comment by kallitokaco** [comment]
PS: the link to the previous Match in the "Current Match" tab is wrong( leads to: "http://hearthstats.net/constructeds/-1/edit")

**Comment by trigun0x2** [comment]
@YiboDuan tried to fix this "-1" error before.

**Comment by kallitokaco** [comment]
I looked over the code but didn't find the update of the matchState but i think this will fix it due to matchUrl in the log is correct for me.

In:"companion/src/main/scala/net/hearthstats/ui/MatchPanel.scala"
after 112 add 
matchState.lastMatchUrl= m.matchUrl + "/edit";

**Comment by kallitokaco** [comment]
Now i know the probably the reason for this problem: Multiple displays and i'm running an eGPU(That means that, my internal GPU as well as my external could render the content of the window,) and this seems to affect your way of grabbing the content of the window. If i only attach a single display without my eGPU it works.
