### ISSUE TITLE
exception of deck detection

### ISSUE THREAD

**Issue by lizequn** [HearthStats/HearthStats.net-Uploader#626]
18:58:56.686 [atcher-5] ERROR       n.h.ui.log.Log - <div class="error"><span class="ts">[18:58:56]</span>&nbsp; empty.maxBy</div>
java.lang.UnsupportedOperationException: empty.maxBy
	at scala.collection.TraversableOnce$class.maxBy(TraversableOnce.scala:221) ~[HearthStats.exe:na]
	at scala.collection.AbstractTraversable.maxBy(Traversable.scala:104) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser.net$hearthstats$game$imageanalysis$DeckAnalyser$$identifyCard(DeckAnalyser.scala:95) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser$$anonfun$identifyCards$1.apply$mcVI$sp(DeckAnalyser.scala:68) ~[HearthStats.exe:na]
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser.identifyCards(DeckAnalyser.scala:62) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser.identifyDeck(DeckAnalyser.scala:30) ~[HearthStats.exe:na]
	at net.hearthstats.ui.ExportDeckBox$ExportDeckBoxImpl.captureDeck(ExportDeckBox.scala:269) ~[HearthStats.exe:na]
	at net.hearthstats.ui.ExportDeckBox$ExportDeckBoxImpl.handleScreenEvent(ExportDeckBox.scala:220) ~[HearthStats.exe:na]
	at net.hearthstats.ui.ExportDeckBox$ExportDeckBoxImpl$$anonfun$3.applyOrElse(ExportDeckBox.scala:204) [HearthStats.exe:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) [HearthStats.exe:na]
	at net.hearthstats.util.ActorObservable$$anonfun$addReceive$2$$anon$1.aroundReceive(ActorObservable.scala:22) [HearthStats.exe:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [HearthStats.exe:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [HearthStats.exe:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [HearthStats.exe:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [HearthStats.exe:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [HearthStats.exe:na]

**Comment by tyrcho** [comment]
This could be because the card list could not be downloaded at the start of the application. Could you restart HS Companion, retry, and if the issue is still there send the complete log file ?
