### ISSUE TITLE
Hello can't add decks

### ISSUE THREAD

**Issue by Tibygod** [HearthStats/HearthStats.net-Uploader#632]
Hello, i can't add decks from site or export, if you can find time for me i will be glad, thank you 

09:52:40.751 [    main] WARN      n.h.c.UserConfig - Unable to interpret value en, using default en instead
09:52:40.847 [    main] INFO  .VideoEncoderFactory - Instantiation interface net.hearthstats.modules.video.VideoEncoder from SPI
09:52:41.316 [    main] ERROR    n.h.hstatsapi.API - Error communicating with HearthStats.net (GET users/premium)
java.io.IOException: Server returned HTTP response code: 500 for URL: http://hearthstats.net/api/v1/users/premium?userkey=your_userkey_here
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[na:1.8.0_31]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.8.0_31]
	at net.hearthstats.hstatsapi.API._get(API.scala:109) [HearthStats.exe:na]
	at net.hearthstats.hstatsapi.API.premiumUserId$lzycompute(API.scala:30) [HearthStats.exe:na]
	at net.hearthstats.hstatsapi.API.premiumUserId(API.scala:30) [HearthStats.exe:na]
	at net.hearthstats.modules.ReplayHandler.<init>(ReplayHandler.scala:23) [HearthStats.exe:na]
	at net.hearthstats.Main.<init>(Main.scala:93) [HearthStats.exe:na]
	at net.hearthstats.win.HearthStatsWin$.delayedEndpoint$net$hearthstats$win$HearthStatsWin$1(HearthStatsWin.scala:20) [HearthStats.exe:na]
	at net.hearthstats.win.HearthStatsWin$delayedInit$body.apply(HearthStatsWin.scala:15) [HearthStats.exe:na]
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40) [HearthStats.exe:na]
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12) [HearthStats.exe:na]
	at scala.App$$anonfun$main$1.apply(App.scala:76) [HearthStats.exe:na]
	at scala.App$$anonfun$main$1.apply(App.scala:76) [HearthStats.exe:na]
	at scala.collection.immutable.List.foreach(List.scala:381) [HearthStats.exe:na]
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35) [HearthStats.exe:na]
	at scala.App$class.main(App.scala:76) [HearthStats.exe:na]
	at net.hearthstats.win.HearthStatsWin$.main(HearthStatsWin.scala:15) [HearthStats.exe:na]
	at net.hearthstats.win.HearthStatsWin.main(HearthStatsWin.scala) [HearthStats.exe:na]
09:52:41.318 [    main] INFO     n.h.hstatsapi.API - You are not a premium user
09:52:41.324 [tQueue-0] INFO     n.h.hstatsapi.API - API get result = {"status":"error","message":"User Key Error"}
09:52:41.329 [    main] WARN        n.h.ui.log.Log - <div class="break">&nbsp;</div><div class="warn"><span class="ts">[09:52:41]</span>&nbsp; You don't have premium subscription, videos won't be uploaded to hearthstats.net</div>
09:52:41.332 [    main] INFO  .FileUploaderFactory - Dummy instantiation for interface net.hearthstats.modules.upload.FileUploader :class net.hearthstats.modules.upload.DummyFileUploader
09:52:41.339 [tQueue-0] ERROR    n.h.hstatsapi.API - User Key Error
09:52:41.340 [tQueue-0] WARN        n.h.ui.log.Log - <div class="warn"><span class="ts">[09:52:41]</span>&nbsp; no deck were returned from Hearthstats.net. Either you have not created a deck or the site is down</div>
09:52:41.580 [    main] INFO  net.hearthstats.Main - **********************************************************************
09:52:41.580 [    main] INFO  net.hearthstats.Main -   Starting HearthStats Companion 0.21.1 on WINDOWS
09:52:41.581 [    main] INFO  net.hearthstats.Main -   os.name=Windows 8.1
09:52:41.581 [    main] INFO  net.hearthstats.Main -   os.version=6.3
09:52:41.582 [    main] INFO  net.hearthstats.Main -   os.arch=x86
09:52:41.582 [    main] INFO  net.hearthstats.Main -   java.runtime.version=1.8.0_31-b13
09:52:41.583 [    main] INFO  net.hearthstats.Main -   java.class.path=E:\Games\HearthStats.exe;anything;companion-0.21.1.jar;updater-0.21.1.jar;scala-library-2.11.4.jar;scala-swing_2.11-1.0.1.jar;macros_2.11-0.7.3.jar;scala-reflect-2.11.2.jar;akka-actor_2.11-2.3.6.jar;config-1.2.1.jar;nscala-time_2.11-1.4.0.jar;joda-time-2.4.jar;joda-convert-1.2.jar;grizzled-slf4j_2.11-1.0.2.jar;logback-classic-1.1.2.jar;logback-core-1.1.2.jar;commons-lang3-3.3.1.jar;commons-io-2.4.jar;jna-platform-4.0.0.jar;jna-4.0.0.jar;ini4j-0.5.2.jar;jai_imageio-1.1.jar;javaocr-core-1.0.jar;javaocr-plugin-awt-1.0.jar;javaocr-plugin-cluster-1.0.jar;commons-math-2.1.jar;javaocr-plugin-fir-1.0.jar;javaocr-plugin-moment-1.0.jar;javaocr-plugin-morphology-1.0.jar;json-simple-1.1.1.jar;miglayout-swing-4.2.jar;miglayout-core-4.2.jar;JGoogleAnalyticsTracker-1.2.0.jar;slf4j-api-1.7.6.jar;jackson-module-scala_2.11-2.4.3.jar;jackson-core-2.4.3.jar;jackson-annotations-2.4.3.jar;jackson-databind-2.4.3.jar;paranamer-2.6.jar;jsr305-2.0.1.jar;guava-15.0.jar;video-0.21.1.jar;xuggle-xuggler-5.4.jar;commons-cli-1.1.jar;google-api-services-youtube-v3-rev107-1.18.0-rc.jar;google-api-client-1.18.0-rc.jar;google-oauth-client-1.18.0-rc.jar;google-http-client-jackson2-1.18.0-rc.jar;google-http-client-1.18.0-rc.jar;google-oauth-client-jetty-1.18.0-rc.jar;google-oauth-client-java6-1.18.0-rc.jar;jetty-6.1.26.jar;jetty-util-6.1.26.jar;servlet-api-2.5-20081211.jar;google-collections-1.0.jar;aws-java-sdk-1.6.0.jar;commons-logging-1.1.1.jar;httpclient-4.2.jar;httpcore-4.2.jar;commons-codec-1.3.jar
09:52:41.583 [    main] INFO  net.hearthstats.Main -   java.library.path=C:\Program Files (x86)\Java\jre1.8.0_31\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Java\jre1.8.0_31\bin;.
09:52:41.584 [    main] INFO  net.hearthstats.Main -   user.language=en
09:52:41.584 [    main] INFO  net.hearthstats.Main - **********************************************************************
09:52:42.051 [    main] INFO        n.h.ui.log.Log - <div class="std"><span class="ts">[09:52:42]</span>&nbsp; Using existing Hearthstone log config C:\Users\Tibi\AppData\Local\Blizzard\Hearthstone\log.config</div>
09:52:42.052 [    main] INFO        n.h.ui.log.Log - <div class="break">&nbsp;</div><div class="welcome">HearthStats Companion v0.21.1</div>
09:52:42.053 [    main] INFO        n.h.ui.log.Log - <div class="break">&nbsp;</div><div class="help">1 - Set your deck slots on the "Decks" tab</div>
09:52:42.053 [    main] INFO        n.h.ui.log.Log - <div class="help">2 - Run Hearthstone in <strong>WINDOWED</strong> mode</div>
09:52:42.053 [    main] INFO        n.h.ui.log.Log - <div class="help">3 - Look for event notifications in this log and bottom right of screen</div>
09:52:42.058 [    main] INFO        n.h.ui.log.Log - <div class="help">4 - <a href="http://goo.gl/lMbdzg">Submit feedback here</a> (please copy and paste your log file in E:\Games\log.txt)</div>
09:52:42.063 [    main] INFO     n.h.c.GameMonitor - HearthStats Companion started
09:52:42.096 [tQueue-0] INFO        n.h.ui.log.Log - <div class="break">&nbsp;</div><div class="std"><span class="ts">[09:52:42]</span>&nbsp; Checking for updates ...</div>
09:52:42.100 [thread-1] INFO        n.h.ui.log.Log - <div class="std"><span class="ts">[09:52:42]</span>&nbsp; Hearthstone detected</div>
09:52:42.103 [thread-1] INFO    n.h.u.FileObserver - observing file D:\Games\Hearthstone\Hearthstone_Data\output_log.txt
09:52:42.104 [thread-1] INFO        n.h.ui.log.Log - <div class="std"><span class="ts">[09:52:42]</span>&nbsp; Observing Hearthstone log file : D:\Games\Hearthstone\Hearthstone_Data\output_log.txt</div>
09:52:43.481 [tQueue-0] INFO        n.h.ui.log.Log - <div class="std"><span class="ts">[09:52:43]</span>&nbsp; Latest version available: v0.21.1</div>
09:52:56.910 [atcher-7] INFO     n.h.hstatsapi.API - API get result = {"status":"error","message":"User Key Error"}
09:52:56.911 [atcher-7] ERROR    n.h.hstatsapi.API - User Key Error
09:52:57.139 [atcher-7] ERROR ox$ExportDeckBoxImpl - empty.maxBy
java.lang.UnsupportedOperationException: empty.maxBy
	at scala.collection.TraversableOnce$class.maxBy(TraversableOnce.scala:221) ~[HearthStats.exe:na]
	at scala.collection.AbstractTraversable.maxBy(Traversable.scala:104) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser.net$hearthstats$game$imageanalysis$DeckAnalyser$$identifyCard(DeckAnalyser.scala:95) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser$$anonfun$identifyCards$1.apply$mcVI$sp(DeckAnalyser.scala:68) ~[HearthStats.exe:na]
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser.identifyCards(DeckAnalyser.scala:62) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser.identifyDeck(DeckAnalyser.scala:30) ~[HearthStats.exe:na]
	at net.hearthstats.ui.ExportDeckBox$ExportDeckBoxImpl.captureDeck(ExportDeckBox.scala:269) ~[HearthStats.exe:na]
	at net.hearthstats.ui.ExportDeckBox$ExportDeckBoxImpl.handleScreenEvent(ExportDeckBox.scala:220) ~[HearthStats.exe:na]
	at net.hearthstats.ui.ExportDeckBox$ExportDeckBoxImpl$$anonfun$3.applyOrElse(ExportDeckBox.scala:204) [HearthStats.exe:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) [HearthStats.exe:na]
	at net.hearthstats.util.ActorObservable$$anonfun$addReceive$2$$anon$1.aroundReceive(ActorObservable.scala:22) [HearthStats.exe:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [HearthStats.exe:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [HearthStats.exe:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [HearthStats.exe:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [HearthStats.exe:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [HearthStats.exe:na]
09:52:57.141 [atcher-7] ERROR       n.h.ui.log.Log - <div class="error"><span class="ts">[09:52:57]</span>&nbsp; empty.maxBy</div>
java.lang.UnsupportedOperationException: empty.maxBy
	at scala.collection.TraversableOnce$class.maxBy(TraversableOnce.scala:221) ~[HearthStats.exe:na]
	at scala.collection.AbstractTraversable.maxBy(Traversable.scala:104) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser.net$hearthstats$game$imageanalysis$DeckAnalyser$$identifyCard(DeckAnalyser.scala:95) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser$$anonfun$identifyCards$1.apply$mcVI$sp(DeckAnalyser.scala:68) ~[HearthStats.exe:na]
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser.identifyCards(DeckAnalyser.scala:62) ~[HearthStats.exe:na]
	at net.hearthstats.game.imageanalysis.DeckAnalyser.identifyDeck(DeckAnalyser.scala:30) ~[HearthStats.exe:na]
	at net.hearthstats.ui.ExportDeckBox$ExportDeckBoxImpl.captureDeck(ExportDeckBox.scala:269) ~[HearthStats.exe:na]
	at net.hearthstats.ui.ExportDeckBox$ExportDeckBoxImpl.handleScreenEvent(ExportDeckBox.scala:220) ~[HearthStats.exe:na]
	at net.hearthstats.ui.ExportDeckBox$ExportDeckBoxImpl$$anonfun$3.applyOrElse(ExportDeckBox.scala:204) [HearthStats.exe:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) [HearthStats.exe:na]
	at net.hearthstats.util.ActorObservable$$anonfun$addReceive$2$$anon$1.aroundReceive(ActorObservable.scala:22) [HearthStats.exe:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [HearthStats.exe:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [HearthStats.exe:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [HearthStats.exe:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [HearthStats.exe:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [HearthStats.exe:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [HearthStats.exe:na]

**Comment by tyrcho** [comment]
I think you only need to enter the user key in the options tab. Get it from http://hearthstats.net/uploader

**Comment by Tibygod** [comment]
Thank you, is ok now, and sorry for this.
 

     On Tuesday, January 27, 2015 1:18 PM, Michel Daviot <notifications@github.com> wrote:
   

 I think you only need to enter the user key in the options tab. Get it from http://hearthstats.net/uploader—

**Comment by tyrcho** [comment]
No problem
