### ISSUE TITLE
API error with 500 return code.

### ISSUE THREAD

**Issue by ueli** [HearthStats/HearthStats.net-Uploader#646]
Hi,
There seams to be a problem with the API.
Lately I often get get 'Could not submit the match to Hearthstats.net, API error'.

Logfile sniped:

6:14:38.335 [cher-148] ERROR    n.h.hstatsapi.API - Error communicating with HearthStats.net (POST matches/new)
java.io.IOException: Server returned HTTP response code: 500 for URL: http://hearthstats.net/api/v1/matches/new?userkey=XXXXXXXXXXXXXXXXXXXXX
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1839) ~[na:1.8.0_31]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[na:1.8.0_31]
        at net.hearthstats.hstatsapi.API._post(API.scala:179) [HearthStatsUploader-OSX.jar:na]
        at net.hearthstats.hstatsapi.API.createMatch(API.scala:84) [HearthStatsUploader-OSX.jar:na]
        at net.hearthstats.hstatsapi.MatchUtils.submitMatchImpl(MatchUtils.scala:117) [HearthStatsUploader-OSX.jar:na]
        at net.hearthstats.hstatsapi.MatchUtils.submitMatchResult(MatchUtils.scala:44) [HearthStatsUploader-OSX.jar:na]
        at net.hearthstats.companion.GameMonitor.net$hearthstats$companion$GameMonitor$$endGameImpl(GameMonitor.scala:324) [HearthStatsUploader-OSX.jar:na]
        at net.hearthstats.companion.GameMonitor$$anonfun$4.applyOrElse(GameMonitor.scala:155) [HearthStatsUploader-OSX.jar:na]
        at net.hearthstats.companion.GameMonitor$$anonfun$4.applyOrElse(GameMonitor.scala:149) [HearthStatsUploader-OSX.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223) [HearthStatsUploader-OSX.jar:na]
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219) [HearthStatsUploader-OSX.jar:na]
        at net.hearthstats.companion.GameMonitor.net$hearthstats$companion$GameMonitor$$handleLogEvent(GameMonitor.scala:177) [HearthStatsUploader-OSX.jar:na]
        at net.hearthstats.companion.GameMonitor$$anonfun$2.applyOrElse(GameMonitor.scala:138) [HearthStatsUploader-OSX.jar:na]
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465) [HearthStatsUploader-OSX.jar:na]
        at net.hearthstats.util.ActorObservable$$anonfun$addReceive$2$$anon$1.aroundReceive(ActorObservable.scala:22) [HearthStatsUploader-OSX.jar:na]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [HearthStatsUploader-OSX.jar:na]
        at akka.actor.ActorCell.invoke(ActorCell.scala:487) [HearthStatsUploader-OSX.jar:na]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [HearthStatsUploader-OSX.jar:na]
        at akka.dispatch.Mailbox.run(Mailbox.scala:220) [HearthStatsUploader-OSX.jar:na]
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [HearthStatsUploader-OSX.jar:na]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [HearthStatsUploader-OSX.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [HearthStatsUploader-OSX.jar:na]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [HearthStatsUploader-OSX.jar:na]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [HearthStatsUploader-OSX.jar:na]
16:14:38.338 [cher-148] WARN        n.h.ui.log.Log - <div class="break">&nbsp;</div><div class="warn"><span class="ts">[16:14:38]</span>&nbsp; Could not submit the match to Hearthstats.net, API error</div>
16:14:38.380 [cher-148] INFO  n.h.c.CompanionState - reset companion state

Cheers,
- ueli

**Comment by trigun0x2** [comment]
This should be fixed now. The problem was from our side.

**Comment by ueli** [comment]
Thanks, it works again.
- ueli
